name: Run Server

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      
      - name: Checkout Repo Content
        uses: actions/checkout@v2 # checkout the repository content

      - name: Dependency Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Install Dependencies
        run: |
          brew install ngrok
          pip install flask
      - name: Run Server # run main.py
        env:
          NGROK_KEY: ${{ secrets.NGROK_KEY }}
        run: |
          ngrok config add-authtoken $NGROK_KEY
          python main.py
