name: Run Server

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      
      - name: Checkout Repo Content
        uses: actions/checkout@v2 # checkout the repository content

      - name: Dependency Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Install Dependencies
        run: |
          brew install ngrok
          pip install flask
      - name: Run Server # run main.py
        env:
          NGROK_KEY: ${{ secrets.NGROK_KEY }}
        run: |
          ngrok config add-authtoken $NGROK_KEY
          python main.py
      - name: Stage, Commit, and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add . # Stage all changed files
          git commit -m "Automated commit after running server" || echo "No changes to commit" # Commit the changes, only if there are changes
          git push origin HEAD:main # Push the changes to the main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication

